name: Checks

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '17.x'
      - name: Setup env
        run: yarn install
      - name: Check lint
        run: yarn run lint
      - name: React Native Android Build APK
        uses: realabbas/Github-Actions-React-Native@v1.1.2
